{nama:"AAQILAH AL SAHWA", asal:"MIS AL YUSUFIYAH BULUSPESANTREN", ruang:"2", gelombang:"2", username:"260216", password:"260216", kelas:"KELAS REGULER"},
{nama:"AHMAD MAULANA PUTRA ", asal:"SD IT HASANAH FATIMIYAH ", ruang:"1", gelombang:"2", username:"260003", password:"260003", kelas:"KELAS REGULER"},
{nama:"AMRI FAIZAL MUTAMIM", asal:"MIS SULTAN AGUNG 1 KALIPOH", ruang:"1", gelombang:"2", username:"260223", password:"260223", kelas:"KELAS REGULER"},
{nama:"ARSYAH SATRIAYADI PUTRA", asal:"MI MA'ARIF JOJOGAN", ruang:"1", gelombang:"2", username:"260215", password:"260215", kelas:"KELAS REGULER"},
{nama:"AURELIA NAURA ZAFARANI", asal:"SDIT VIP AL-HUDA", ruang:"2", gelombang:"2", username:"260048", password:"260048", kelas:"KELAS REGULER"},
{nama:"ELVA DINDA APRELIA", asal:"MTS N 2 KULON PROGO", ruang:"2", gelombang:"2", username:"260224", password:"260224", kelas:"KELAS REGULER"},
{nama:"FAHRI AKBAR", asal:"SDN 1 JOGOSIMO", ruang:"1", gelombang:"2", username:"260226", password:"260226", kelas:"KELAS REGULER"},
{nama:"MIFTAH SUNANDAR AL ANSORI", asal:"SDN 1 DOROWATI", ruang:"1", gelombang:"2", username:"260225", password:"260225", kelas:"KELAS REGULER"},
{nama:"MUHAMMAD HABIB AL REVANNO", asal:"UPT SD NEGERI SIMPANG SENDER SELATAN ", ruang:"1", gelombang:"2", username:"260191", password:"260191", kelas:"KELAS REGULER"},
{nama:"MUTIARA UZMA AL FIRDAUS", asal:"SDN BINTARO 14 PAGI", ruang:"2", gelombang:"2", username:"260217", password:"260217", kelas:"KELAS REGULER"},
{nama:"RIZQI GUSTI PUTRA", asal:"MIS SULTAN AGUNG 1 KALIPOH", ruang:"1", gelombang:"2", username:"260222", password:"260222", kelas:"KELAS REGULER"},
{nama:"SAJIDA AZZA ROKHMI", asal:"SD NEGERI GROGOL BENINGSARI", ruang:"2", gelombang:"2", username:"260094", password:"260094", kelas:"KELAS REGULER"},
{nama:"SURFINA ALYA FIRZANAH", asal:"SDIT ATSSURAYYA", ruang:"2", gelombang:"2", username:"260160", password:"260160", kelas:"KELAS REGULER"},
{nama:"TASYA AMELIA", asal:"SDN TUKINGGEDONG", ruang:"2", gelombang:"2", username:"260033", password:"260033", kelas:"KELAS REGULER"},
{nama:"TUTI ALAWIYAH", asal:"SDN 2 KARANGSARI", ruang:"2", gelombang:"2", username:"260064", password:"260064", kelas:"KELAS REGULER"},
{nama:"ULFA KHAIRUNNISA", asal:"SDN 1 BUMIREJO", ruang:"2", gelombang:"2", username:"260096", password:"260096", kelas:"KELAS REGULER"},
{nama:"WASISTO JATI SADONO", asal:"MI NU YAPIKA", ruang:"1", gelombang:"2", username:"260211", password:"260211", kelas:"KELAS REGULER"},
{nama:"YUNA AURORA DWI ALEXXA", asal:"SD N 1 TAMBAKMULYO", ruang:"2", gelombang:"2", username:"260122", password:"260122", kelas:"KELAS REGULER"},
{nama:"ZAKIYYATUL'ULYA", asal:"MI NURUL SULAIMAN", ruang:"2", gelombang:"2", username:"260098", password:"260098", kelas:"KELAS REGULER"},
{nama:"ZIDNI NUROL FADILAH", asal:"MIS SULTAN AGUNG 1 KALIPOH", ruang:"2", gelombang:"2", username:"260221", password:"260221", kelas:"KELAS REGULER"}
];
