const database = [
{nama:"ADAM DAFFA MUBAROK", asal:"SD NEGRI 5 KUTOSARI, KEBUMEN", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260030", password:"260030"},
{nama:"AFIGO INDRA PRATAMA", asal:"SDN 2 LEMBU PURWO", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260039", password:"260039"},
{nama:"AHMAD MAULANA PUTRA ", asal:"SD IT HASANAH FATIMIYAH ", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260003", password:"260003"},
{nama:"ALIF ACHMAD FIQRI", asal:"SD AYAMPUTIH", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260020", password:"260020"},
{nama:"ALIF ARDIANSYAH", asal:"SDN SUROTURUNAN 2", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260055", password:"260055"},
{nama:"ARRIDHO FAUHAN PUTRA", asal:"SDN 2 NEGARA AJITUA", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260071", password:"260071"},
{nama:"AZKA HAFIZH AL HADAD MUHAMMAD ", asal:"SDN 02 TERSOBO", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260046", password:"260046"},
{nama:"DAMAR SETYO PANGESTU", asal:"MISAL HIDAYAH KARANGTANJUNG ", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260057", password:"260057"},
{nama:"FARHAN FAUZIY", asal:"SDS EKA TJIPTA KENCANA MARAU", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260087", password:"260087"},
{nama:"FIRZA ADITYA PRATAMA", asal:"SD N 10 KUNANGAN PARIK RANTANG", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260097", password:"260097"},
{nama:"ILYAS FIRMANSYAH", asal:"SD NEGERI GADINGPASAR", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260065", password:"260065"},
{nama:"MAHBUB JUNAYDI", asal:"MIS WOTBUWONO KLIRONG", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260052", password:"260052"},
{nama:"MALIK MUKHAYAT ", asal:"SD NEGERI TAMBAHARJO", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260081", password:"260081"},
{nama:"MAMBA'UL ULUM", asal:"SDN,2 BRECONG", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260060", password:"260060"},
{nama:"MAULANA ALIF AFRIANSYAH", asal:"MIS SULTAN AGUNG 2 KALIPOH", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260079", password:"260079"},
{nama:"MUCHDLOR SYAHRONI", asal:"SD N AYAMPUTIH", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260038", password:"260038"},
{nama:"MUHAMAD FATNAM HAFIDZ", asal:"SDN 1 TLOGODEPOK", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260078", password:"260078"},
{nama:"MUHAMMAD HAFIZ FURQONI", asal:"SDN SRUWOHDUKUH", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260061", password:"260061"},
{nama:"MUHAMMAD ZIDAN SYAHPUTRA", asal:"SD NEGERI BLENGORKULON", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260068", password:"260068"},
{nama:"NAIBUL FATA", asal:"MI MAARIF JOJOGAN", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260058", password:"260058"},
{nama:"RAHMAT ALI AKHBAR", asal:"SDN 2 TAMBAKMUYO", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260090", password:"260090"},
{nama:"REKI MUTTAQIN", asal:"SD NEGERI PENEKET", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260031", password:"260031"},
{nama:"RIFKI MUKHTARULLOH ", asal:"SDN 3 SIDOLUHUR ", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260032", password:"260032"},
{nama:"SATYA JAGAKARSA", asal:"SDN 2 ABEAN", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260073", password:"260073"},
{nama:"SYAFIQ ADIBUL UMAM", asal:"MIN 2 KEBUMEN", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"260002", password:"260002"},
{nama:"AGAM ABDILLAH PRATAMA", asal:"MI NU YAPIKA", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260109", password:"260109"},
{nama:"AHZA KAFA PRIADI", asal:"SD NEGERI 1 BOJONGSARI", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260134", password:"260134"},
{nama:"ALFIAN ADI PUTRA PRATAMA", asal:"SDN 1 KEDUNGWINANGUN", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260137", password:"260137"},
{nama:"ALMAS JA'FARY", asal:"MIS MA'ARIF BANJARSARI", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260135", password:"260135"},
{nama:"AZZAM PRATAMA ", asal:"SD N AMPELSARI ", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260112", password:"260112"},
{nama:"DIMAS BAYU PAMUNGKAS", asal:"SDN 04 KUWAYUHAN", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260115", password:"260115"},
{nama:"DISTA AJI SAPUTRA ", asal:"SD NEGERI 1 LOGANDU ", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260107", password:"260107"},
{nama:"FAJAR HASYIM MARZUKI", asal:"SD N ADIKARTO", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260120", password:"260120"},
{nama:"FAQIH ABDURRAHMAN MAWARDI", asal:"SDN NEGERI PENEKET", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260104", password:"260104"},
{nama:"FARREL KHAIRUL ANAM", asal:"-", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260126", password:"260126"},
{nama:"HUSAIN ANIS ABDILLAH", asal:"SD N 2 TRIKARSO", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260113", password:"260113"},
{nama:"IKHLASHUL AMAL", asal:"SD NEGERI KEDUNGAGUNG ", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260106", password:"260106"},
{nama:"MIFTAHUDIN", asal:"MIS DIPANEGARA", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260127", password:"260127"},
{nama:"MIFTAKUL ULUM", asal:"MI SULTAN AGUNG WATU KELIR", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260118", password:"260118"},
{nama:"MOHAMAD ZAINUL MUSTOFA", asal:"SD NEGERI 1 KRITIG", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260130", password:"260130"},
{nama:"MOHAMMAD TORIK ASSALAM", asal:"MI MA'ARIF MANGUNRANAN", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260116", password:"260116"},
{nama:"MUHAMAD ABROR MAULANA", asal:"SD N ROWOREJO", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260100", password:"260100"},
{nama:"MUHAMAD SAFIQ RAMADHAN", asal:"MI MA'ARIF MANGUNRANAN", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260117", password:"260117"},
{nama:"MUHAMMAD ABIDARR AL GHIFARY", asal:" SD N 2 BANDUNG ", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260099", password:"260099"},
{nama:"MUHAMMAD NAUFAL HAKIM", asal:"MI NU YAPIKA", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260110", password:"260110"},
{nama:"NANDO BIBIT NIRWANA", asal:"SDN WERGONAYAN ", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260108", password:"260108"},
{nama:"NURIL ARIFIN", asal:"SD NEGERI ARJOWINANGUN ", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260114", password:"260114"},
{nama:"RAHMAT SYAMSUL ARIFIN", asal:"SDN SINGOSARI", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260133", password:"260133"},
{nama:"RIKO AJI PANGESTU", asal:"SD N DUKUHREJO", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260102", password:"260102"},
{nama:"UMAR SIDIK", asal:"SDN 1 AYAMPUTIH", ruang:"2", gelombang:"1", kelas:"KELAS REGULER", username:"260150", password:"260150"},
{nama:"ABDUL ROZAK AL FATIH", asal:"MI NU YAPIKA", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260188", password:"260188"},
{nama:"ACHMAD FAIZUL AL ATAN", asal:"MI NU YAPIKA", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260201", password:"260201"},
{nama:"ADITYA FADILLAH", asal:"MIS MA'ARIF KEMANGGUAN", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260174", password:"260174"},
{nama:"AHMAD MUBAROK", asal:"MIS MA'ARIF WAGIRPANDAN", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260165", password:"260165"},
{nama:"AHMAD MUWA FIQ AL AZZAM", asal:"MIS MA'ARIF WAGIRPANDAN", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260167", password:"260167"},
{nama:"AKHMAD MISBAKHUDIN", asal:"MIS GIWANGRETNO SRUWENG", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260162", password:"260162"},
{nama:"ALIF RAMADHAN", asal:"MI NU YAPIKA", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260203", password:"260203"},
{nama:"ANUGRAH FAJAR RAMADHANI", asal:"SDIT AMALIA PODOURIP", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260205", password:"260205"},
{nama:"AZZAM TSAAQIB RAFANDRA", asal:"SD NEGERI 1 LOGEDE", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260204", password:"260204"},
{nama:"FANDI ADIANSYAH", asal:"SD NEGERI 1 SRATI", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260171", password:"260171"},
{nama:"ILYAS SAEFUDIN", asal:"SD NEGERI 2 LUMBU", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260177", password:"260177"},
{nama:"JEKLIARAYA", asal:"SDN PODOURIP", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260207", password:"260207"},
{nama:"KHAYRI RAHMAN AL ADHNI", asal:"SD NEGERI 5 SIMPANG PEMATANG", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260155", password:"260155"},
{nama:"LABIB HABIBI ARROZI ", asal:"SD NEGRI PESALAKAN ", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260181", password:"260181"},
{nama:"MAULANA SYARIF SAKBAN ", asal:"MI MA'ARIF KEMANGGUAN", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260193", password:"260193"},
{nama:"MOKHAMAD NAJJIH ADIB AN'NAS", asal:"SD NEGERI 1 KARANGKEMBANG", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260154", password:"260154"},
{nama:"MUHAMAD GILANG SAPUTRA", asal:"MIS MA'ARIF WAGIRPANDAN", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260186", password:"260186"},
{nama:"MUHAMAD YAHYA", asal:"SD NEGERI 1 KRITIG", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260180", password:"260180"},
{nama:"MUHAMMAD QAIS RAFAEL", asal:"SD NEGRI 2 LUNDONG", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260199", password:"260199"},
{nama:"MUHAMMAD ZIDANE RAMADHAN ", asal:"SDN MIRIT PETIKUSAN ", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260187", password:"260187"},
{nama:"RESKY", asal:"SD NEGERI AYAMPUTIH", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260178", password:"260178"},
{nama:"RISKI WIDIYANTO", asal:"SD NEGERI 1 KARANGKEMBANG", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260170", password:"260170"},
{nama:"RIZAL AZHARI", asal:"SDN ROWOREJO", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260190", password:"260190"},
{nama:"SIDIQ MA'ARIF", asal:"SDN 2 KEBULUSAN", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260206", password:"260206"},
{nama:"SYAFIQ ALAWY", asal:"SDN BLENGORKULON", ruang:"3", gelombang:"1", kelas:"KELAS REGULER", username:"260209", password:"260209"},
{nama:"ALISA PUTRI OKTAFIANI", asal:"SDN 2 LEMBUPURWO", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260026", password:"260026"},
{nama:"ASMA'UL HUSNA", asal:"MI MA'ARIF JOJOGAN", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260022", password:"260022"},
{nama:"AUFA LEILA ALZENA", asal:"SDN 3 SIDOLUHUR", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260035", password:"260035"},
{nama:"AURELIA NAURA ZAFARANI", asal:"SDIT VIP AL-HUDA", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260048", password:"260048"},
{nama:"AZAHRA PURWANTI", asal:"SDN3 SIDOLUHUR", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260059", password:"260059"},
{nama:"AZIZAH NURUL AINY", asal:"SDN 2 LEMBUPURWO", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260025", password:"260025"},
{nama:"DESISKA RAISA ADILA", asal:"SD NEGERI 4 PURBOWANGI", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260016", password:"260016"},
{nama:"DINDA MARDHIYATUZZUHRO", asal:"SD NEGERI 2 SIDOLUHUR", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260023", password:"260023"},
{nama:"ERLINA AZNII NAYLA", asal:"SD NEGERI 2 SIDOLUHUR", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260042", password:"260042"},
{nama:"FATMA HAFIVATUL NUR KUMALA", asal:"SDN 2 LEMBUPURWO", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260027", password:"260027"},
{nama:"FILDANIA NUR ASYIFAH", asal:"SD NEGERI 2 SINUNGREJO", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260066", password:"260066"},
{nama:"ITSNA MULAZIMATUL HASANAH", asal:"SDN 02 LEMBUPURWO", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260024", password:"260024"},
{nama:"JIHAN HANIFAH ", asal:"MI ALMASRURIYAH", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260034", password:"260034"},
{nama:"KEYSHA RAMADHANI AZZAHRA", asal:"SD N 2 LEMBUPURWO", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260040", password:"260040"},
{nama:"LAILA ATIKOH", asal:"SD NEGERI 3 KLAPASAWIT", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260051", password:"260051"},
{nama:"LULU AZKIA NAFISAH", asal:"SDN 1 LUNDONG", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260011", password:"260011"},
{nama:"MUTIA NUR'AINI", asal:"SDN 1 LUNDONG", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260010", password:"260010"},
{nama:"NAIRA FATIH", asal:"MI MA'ARIF JOJOGAN", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260045", password:"260045"},
{nama:"SAFIRA MAULIDA ROHMAH", asal:"MI KHR ILYAS", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260062", password:"260062"},
{nama:"SYIFA MUTMAINAH", asal:"MI IMAM PURO LUBANG INDANGAN", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260012", password:"260012"},
{nama:"TUTI ALAWIYAH", asal:"SDN 2 KARANGSARI", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260064", password:"260064"},
{nama:"WAFIQ AZIZAH", asal:"MI MA'ARIF JOJOGAN", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260047", password:"260047"},
{nama:"WAWALINA WIDIASTUTI", asal:"SDN 01 LEMBUPURWO", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260028", password:"260028"},
{nama:"YASMIN HANIFAH SALMA", asal:"SD N 1 WERGONAYAN", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260036", password:"260036"},
{nama:"YASMIN KHUMAIROH", asal:"SDN  KARANGGINTUNG 07", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260029", password:"260029"},
{nama:"ZAHRA ASSYIFA", asal:"SDN 009 AIR BALUI", ruang:"4", gelombang:"1", kelas:"KELAS REGULER", username:"260014", password:"260014"},
{nama:"ANIDA ULKHUSNA", asal:"SD N 2 SRATI", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260082", password:"260082"},
{nama:"AUREL SILFILIA", asal:"SD N ROWOREJO", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260101", password:"260101"},
{nama:"AZZA KHOLIFATURRIF'AH", asal:"-", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260124", password:"260124"},
{nama:"CASYA LAIFANO AGUSTRIN", asal:"SDN2 TAMBAKMULYO", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260089", password:"260089"},
{nama:"CELISTA NELVIA AURORA YESHA NURAINI ", asal:"MI MA'ARIF JOJOGAN ", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260083", password:"260083"},
{nama:"EVA RAHMAWATI", asal:"MI SULTAN AGUNG KARANG DUWUR", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260091", password:"260091"},
{nama:"HENY SIDQIYA", asal:"SDN KTANDEGAN 1", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260128", password:"260128"},
{nama:"ISNA KHUMAEROH ", asal:"MI SULTAN AGUNG KARANG DUWUR ", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260092", password:"260092"},
{nama:"JELITA AYU KIRANA", asal:"MI AL-FATA", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260070", password:"260070"},
{nama:"KHARISMA AYU MAHARANI", asal:"SDN 2 GEBANGSARI", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260129", password:"260129"},
{nama:"KHILDA FATIMATUZ ZAHRA HASYIM", asal:"SDN 2 TERSOBO", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260084", password:"260084"},
{nama:"KHOFIFAH INDAH RAMADHANI", asal:"MI MA'ARIF NU CANDIRENGGO", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260132", password:"260132"},
{nama:"LINDA AYU KIRANA", asal:"MI AL-FATA ", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260069", password:"260069"},
{nama:"MARSHA ZAHRA AL FADHILLA", asal:"SDN 1 KUWARISAN", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260111", password:"260111"},
{nama:"MAULIDYA AZ ZAHRA ", asal:"SDN 01 AMBALRESMI", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260095", password:"260095"},
{nama:"MEINISA NISFATUN LAILIYAH", asal:"SDN MIRITPETIKUSAN", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260077", password:"260077"},
{nama:"MELATI DESTIANI", asal:"SDN 1 BOJONGSARI", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260141", password:"260141"},
{nama:"NAURA FAIDA ANAILA", asal:"MIS PLUS JARYUL ULUM", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260088", password:"260088"},
{nama:"NURIN LUTHFIA NAJWA", asal:"SDN AMBALKLIWONAN", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260119", password:"260119"},
{nama:"NURIN NAJWA AZ ZAHRA", asal:"SD NEGERI ROWOREJO", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260080", password:"260080"},
{nama:"RANI FAUZIA NUR AFITA", asal:"SD NEGERI SIDOREJO", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260131", password:"260131"},
{nama:"SAJIDA AZZA ROKHMI", asal:"SD NEGERI GROGOL BENINGSARI", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260094", password:"260094"},
{nama:"SHAFA LUTFI AZMI ", asal:"SD N JOGOMERTAN", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260125", password:"260125"},
{nama:"SUNIA SA'DA ALFIN", asal:"SD N BLATER ", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260140", password:"260140"},
{nama:"ZULFA SALSABILA", asal:"SD NEGERI 2 LOGANDU", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260136", password:"260136"},
{nama:"ZULFAH NUR MAULIDDAH", asal:"SDN 1 NOGORAJI", ruang:"5", gelombang:"1", kelas:"KELAS REGULER", username:"260085", password:"260085"},
{nama:"AGHITSNA QURROTA'AINI", asal:"MIS MA'ARIF KEMANGGUAN", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260183", password:"260183"},
{nama:"ALFIRA RIZQY RAHMAWATI", asal:"MIS MA'ARIF KEMANGGUAN", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260175", password:"260175"},
{nama:"ALLYCIA ZAHRA RAMADHANI", asal:"SD NEGERI 2 KEBULUSAN", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260182", password:"260182"},
{nama:"AMELIA PUTRI RAMADHANI", asal:"MIS MA'ARIF WAGIRPANDAN", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260173", password:"260173"},
{nama:"AQILA SYIFA PUTRI ROSADI", asal:"MIS MA`ARIF NU MANGUNWENI", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260208", password:"260208"},
{nama:"ATIQOH APRIYANTI", asal:"SD NEGERI KEDUNGAGUNG", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260168", password:"260168"},
{nama:"CHANIFAH AZ ZAHRAA", asal:"MI MA'ARIF WAGIRPANDAN", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260169", password:"260169"},
{nama:"FITROTUL ALIFAH", asal:"SD N 1 MEKARSARI", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260148", password:"260148"},
{nama:"HASNA NAMILA", asal:"MIS MA'ARIF WAGIRPANDAN", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260163", password:"260163"},
{nama:"HUSNA FISANGADAH", asal:"SDN 2 BUMIREJO", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260145", password:"260145"},
{nama:"KARISA AMELIA ZAHRA", asal:"MIS MA'ARIF WAGIRPANDAN", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260164", password:"260164"},
{nama:"LUTHFIA ZAHRA TALITA", asal:"MIS GIWANGRETNO", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260189", password:"260189"},
{nama:"NABILAH SYAFIQOH", asal:"SD NEGERI TEPAKYANG", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260192", password:"260192"},
{nama:"NABILAH ZAKIYYAH ZULFAA", asal:"SD NEGERI SUROBAYAN", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260153", password:"260153"},
{nama:"NAELLA KHASNA", asal:"SDN GADUNGREJO", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260210", password:"260210"},
{nama:"NAIMA RAHMA AZIZAH", asal:"SD NEGERI 1 BOJONGSARI", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260202", password:"260202"},
{nama:"NUR ATIKOH", asal:"SD NEGERI 3 KLAPASAWIT", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260172", password:"260172"},
{nama:"ROFI ARINI RAHMAWATI", asal:"SDN 1 BOJONGSARI", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260142", password:"260142"},
{nama:"SELVA PUTRI AYU SETIANINGSIH", asal:"SDN BENER KULON", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260194", password:"260194"},
{nama:"SELVI PUTRI AYU SETIANINGSIH", asal:"SDN BENER KULON", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260196", password:"260196"},
{nama:"SHEILA FANY NURHIDAYAH", asal:"SD NEGERI 2 WAGIRPANDAN", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260166", password:"260166"},
{nama:"SHINTA AULIA RAHMAH", asal:"SDN 1 BOJONGSARI", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260143", password:"260143"},
{nama:"SITTA AULIA RAHMAH", asal:"MIN 1 KEBUMEN", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260152", password:"260152"},
{nama:"SURFINA ALYA FIRZANAH", asal:"SDIT ATSSURAYYA", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260160", password:"260160"},
{nama:"SYIFA LAILA FAUZIYAH", asal:"MADRASAH IBTIDAIYAH SULTAN AGUNG PENIRON", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260200", password:"260200"},
{nama:"VICKY FITRIA ARTANTI", asal:"SDN BENER KULON", ruang:"6", gelombang:"1", kelas:"KELAS REGULER", username:"260197", password:"260197"},
{nama:"MUHAMMAD HABIB AL REVANNO", asal:"UPT SD NEGERI SIMPANG SENDER SELATAN ", ruang:"-", gelombang:"2", kelas:"KELAS REGULER", username:"260191", password:"260191"},
{nama:"ABDUL NAUFAL ABYAN", asal:"MI MA'ARIF TANJUNGSARI KUTOWINANGUN", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260007", password:"260007"},
{nama:"AISYAH NADIFATUL KHANZA", asal:"MI SULTAN AGUNG WATUKELIR", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260151", password:"260151"},
{nama:"ALFI ZAHROTUL JANNAH", asal:"SDN 2 KARANGGADUNG", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260158", password:"260158"},
{nama:"AQILA SAKINATUZZAFIRA", asal:"MI MA'ARIF KRAKAL", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260063", password:"260063"},
{nama:"AQUINA NILAM CAHYA", asal:"MI ALFATAH SUMBERADI", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260037", password:"260037"},
{nama:"ARKAN BADRUT TAUHID", asal:"SDN SUMBERADI", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260147", password:"260147"},
{nama:"ASSYIFA RAYA MUMTAZ", asal:"SD NEGERI 1 JOGOMERTAN", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260043", password:"260043"},
{nama:"AUFAL MAROM", asal:"SD N 2 LUMBU", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260157", password:"260157"},
{nama:"AZKA MAULINA FURAIDA MUBAROK", asal:"MIS MAARIF WIDORO", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260067", password:"260067"},
{nama:"AZZAHROH MAWADAH AZKA", asal:"MI SULTAN AGUNG 2 KALIPOH", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260050", password:"260050"},
{nama:"BAGUS WIRA ATMADJA", asal:"SD N PESAWAHAN ", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260009", password:"260009"},
{nama:"BELVA FARADIZA AQUINA HAQI ", asal:"MI DIPONEGORO 1 PURWOKERTO LOR ", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260156", password:"260156"},
{nama:"CAHYA TRI PAMUNGKAS", asal:"SD NEGERI 2 TANGGERAN", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260161", password:"260161"},
{nama:"DZAKIRA TALITA ZAHRA", asal:"SD NEGERI CILEMPUYANG 03", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260198", password:"260198"},
{nama:"FANESA NIKI AZIZAH", asal:"SD NEGERI 1 BRECONG", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260144", password:"260144"},
{nama:"FATHIN LUTFIA RAHMA", asal:"SDN PATUKREJOMULYO", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260044", password:"260044"},
{nama:"FITRIATURROKHMAH", asal:"SD N 2 TANAHSARI", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260054", password:"260054"},
{nama:"IBNU HAJAR", asal:"SD NEGERI 2 SIDOAGUNG", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260176", password:"260176"},
{nama:"KEYSA CHURROTUL JINAN ", asal:"SD NEGERI 1 SIDOMORO ", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260195", password:"260195"},
{nama:"LAUREN TRI AGUSTINE", asal:"SDN 1 BUMIREJO PURING KEBUMEN", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260004", password:"260004"},
{nama:"M.KHILDAN NAUSADZ ANNAJIH", asal:"SDN PAGEDANGAN ", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260013", password:"260013"},
{nama:"MAULANA KEVIN AFISENA", asal:"SD N PASAR BARU 07 JAKARTA PUSAT", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260021", password:"260021"},
{nama:"MUHAMAD FAJAR ADZIN", asal:"SDN GANDUL 2", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260159", password:"260159"},
{nama:"MUHAMAD GHOZIYAFI SYURAIH", asal:"SDN SUMBERADI", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260146", password:"260146"},
{nama:"MUHAMAD TORIQ MAULANA", asal:"SD NEGERI KEDUNGAGUNG", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260149", password:"260149"},
{nama:"MUHAMMAD 'AFIF", asal:"SD N JOGOSIMO", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260121", password:"260121"},
{nama:"MUHAMMAD ALFIN ZIDNA FAQIH", asal:"MI MA'ARIF KARANGWUNI", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260015", password:"260015"},
{nama:"MUHAMMAD ARSYA DANI ULINNUHA", asal:"MI MA'ARIF WIDORO ", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260086", password:"260086"},
{nama:"NADA AULIYA SALSABILA", asal:"SD N 2 TANAHSARI", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260053", password:"260053"},
{nama:"NAJWA PUTRI ARIFFDA", asal:"SDN PATUKREJOMULYO ", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260138", password:"260138"},
{nama:"NAYLA SYAFIRA", asal:"SD N 1 TAMBAKMULYO", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260019", password:"260019"},
{nama:"NISRINNA NAJWA AZ ZULFA", asal:"SDN 4 NUSAWUNGU", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260076", password:"260076"},
{nama:"NURUL HIKMAH", asal:"SD NEGERI SITIBENTAR", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260185", password:"260185"},
{nama:"REIHANA LATIFAH ZAHRA", asal:"SD N TUKINGGEDONG", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260123", password:"260123"},
{nama:"SABILA WAHYUNI HIDAYAH", asal:"SD NEGERI 1 JOGOPATEN", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260184", password:"260184"},
{nama:"SINDI DWI APRILIA", asal:"SD NEGERI 1 SIDOMORO", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260179", password:"260179"},
{nama:"SYADDAD ABDURRAHMAN AFIQ ", asal:"MI TARBIYATUL ULUM", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260103", password:"260103"},
{nama:"SYAUQI MUHAMMAD", asal:"SDN 1 MEKARSARI", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260049", password:"260049"},
{nama:"TASYA AMELIA", asal:"SDN TUKINGGEDONG", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260033", password:"260033"},
{nama:"ULFA KHAIRUNNISA", asal:"SDN 1 BUMIREJO", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260096", password:"260096"},
{nama:"WILDAN MUSHOFFA AHMAD ", asal:"SDN SINGOSARI ", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260139", password:"260139"},
{nama:"YUNA AURORA DWI ALEXXA", asal:"SD N 1 TAMBAKMULYO", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260122", password:"260122"},
{nama:"ZAKIYYATUL'ULYA", asal:"MI NURUL SULAIMAN", ruang:"-", gelombang:"2", kelas:"KELAS KOMPETISI", username:"260098", password:"260098"},
{nama:"MUCHAMMAD FATICHUN NADA", asal:"SDN 3 SIDOLUHUR", ruang:"1", gelombang:"1", kelas:"KELAS REGULER", username:"20260107", password:"20260107"}
];
